//------------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Runtime Version: 2.0.50727.8937
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

//@cc_on
//@set @debug(off)

//import System.Xml.Serialization;

//
//This source code was auto-generated by xsd, Version=2.0.50727.3038.
//n

///<comentarios/>
//public
//System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") 
//System.SerializableAttribute() 
//System.Diagnostics.DebuggerStepThroughAttribute() 
//System.ComponentModel.DesignerCategoryAttribute("code") 
//System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
//System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/cfd/3", IsNullable=false) 

export class Comprobante {

    emisorField : ComprobanteEmisor;
    
    receptorField : ComprobanteReceptor;
    
    conceptosField : ComprobanteConcepto[];
/*    
    impuestosField : ComprobanteImpuestos;
    
    complementoField : ComprobanteComplemento;
    
    private var addendaField : ComprobanteAddenda;
    */
    versionField : String;
    
    serieField : String;
    
    folioField : String;
    
    //fechaField : DateTime;
    
    selloField : String;
    
    formaDePagoField : String;
    
    noCertificadoField : String;
    
    certificadoField : String;
    
    condicionesDePagoField : String;
    
    subTotalField : number;
    
    descuentoField : number;
    
    descuentoFieldSpecified : boolean;
    
    motivoDescuentoField : String;
    
    tipoCambioField : String;
    
    monedaField : String;
    
    totalField : number;
    
    metodoDePagoField : String;
    
    //private var tipoDeComprobanteField : ComprobanteTipoDeComprobante;
    
    Comprobante() {
        this.versionField = "3.0";
        
    }
    
    ///<comentarios/>
   /*
    public final function get Emisor() : ComprobanteEmisor {
        return this.emisorField;
    }
    public final function set Emisor(value : ComprobanteEmisor) {
        this.emisorField = value;
    }
    
    ///<comentarios/>
    public final function get Receptor() : ComprobanteReceptor {
        return this.receptorField;
    }
    public final function set Receptor(value : ComprobanteReceptor) {
        this.receptorField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlArrayItemAttribute("Concepto", IsNullable=false) 
    function get Conceptos() : ComprobanteConcepto[] {
        return this.conceptosField;
    }
    public final function set Conceptos(value : ComprobanteConcepto[]) {
        this.conceptosField = value;
    }
    
    ///<comentarios/>
    public final function get Impuestos() : ComprobanteImpuestos {
        return this.impuestosField;
    }
    public final function set Impuestos(value : ComprobanteImpuestos) {
        this.impuestosField = value;
    }
    
    ///<comentarios/>
    public final function get Complemento() : ComprobanteComplemento {
        return this.complementoField;
    }
    public final function set Complemento(value : ComprobanteComplemento) {
        this.complementoField = value;
    }
    
    ///<comentarios/>
    public final function get Addenda() : ComprobanteAddenda {
        return this.addendaField;
    }
    public final function set Addenda(value : ComprobanteAddenda) {
        this.addendaField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get version() : System.String {
        return this.versionField;
    }
    public final function set version(value : System.String) {
        this.versionField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get serie() : System.String {
        return this.serieField;
    }
    public final function set serie(value : System.String) {
        this.serieField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get folio() : System.String {
        return this.folioField;
    }
    public final function set folio(value : System.String) {
        this.folioField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get fecha() : System.DateTime {
        return this.fechaField;
    }
    public final function set fecha(value : System.DateTime) {
        this.fechaField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get sello() : System.String {
        return this.selloField;
    }
    public final function set sello(value : System.String) {
        this.selloField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get formaDePago() : System.String {
        return this.formaDePagoField;
    }
    public final function set formaDePago(value : System.String) {
        this.formaDePagoField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get noCertificado() : System.String {
        return this.noCertificadoField;
    }
    public final function set noCertificado(value : System.String) {
        this.noCertificadoField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get certificado() : System.String {
        return this.certificadoField;
    }
    public final function set certificado(value : System.String) {
        this.certificadoField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get condicionesDePago() : System.String {
        return this.condicionesDePagoField;
    }
    public final function set condicionesDePago(value : System.String) {
        this.condicionesDePagoField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get subTotal() : decimal {
        return this.subTotalField;
    }
    public final function set subTotal(value : decimal) {
        this.subTotalField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get descuento() : decimal {
        return this.descuentoField;
    }
    public final function set descuento(value : decimal) {
        this.descuentoField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get descuentoSpecified() : boolean {
        return this.descuentoFieldSpecified;
    }
    public final function set descuentoSpecified(value : boolean) {
        this.descuentoFieldSpecified = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get motivoDescuento() : System.String {
        return this.motivoDescuentoField;
    }
    public final function set motivoDescuento(value : System.String) {
        this.motivoDescuentoField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get TipoCambio() : System.String {
        return this.tipoCambioField;
    }
    public final function set TipoCambio(value : System.String) {
        this.tipoCambioField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get Moneda() : System.String {
        return this.monedaField;
    }
    public final function set Moneda(value : System.String) {
        this.monedaField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get total() : decimal {
        return this.totalField;
    }
    public final function set total(value : decimal) {
        this.totalField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get metodoDePago() : System.String {
        return this.metodoDePagoField;
    }
    public final function set metodoDePago(value : System.String) {
        this.metodoDePagoField = value;
    }
    
    ///<comentarios/>
    
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get tipoDeComprobante() : ComprobanteTipoDeComprobante {
        return this.tipoDeComprobanteField;
    }
    public final function set tipoDeComprobante(value : ComprobanteTipoDeComprobante) {
        this.tipoDeComprobanteField = value;
    }
    */
}

///<comentarios/>
/*
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
*/
export class ComprobanteEmisor {
    
    //domicilioFiscalField : t_UbicacionFiscal;
    
    //expedidoEnField : t_Ubicacion;
    
    rfcField : String;
    
    nombreField : String;
    /*
    ///<comentarios/>
    public final function get DomicilioFiscal() : t_UbicacionFiscal {
        return this.domicilioFiscalField;
    }
    public final function set DomicilioFiscal(value : t_UbicacionFiscal) {
        this.domicilioFiscalField = value;
    }
    
    ///<comentarios/>
    public final function get ExpedidoEn() : t_Ubicacion {
        return this.expedidoEnField;
    }
    public final function set ExpedidoEn(value : t_Ubicacion) {
        this.expedidoEnField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get rfc() : System.String {
        return this.rfcField;
    }
    public final function set rfc(value : System.String) {
        this.rfcField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get nombre() : System.String {
        return this.nombreField;
    }
    public final function set nombre(value : System.String) {
        this.nombreField = value;
    }
    */
}

/*
///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/cfd/3") 
class t_UbicacionFiscal {
    
    private var calleField : System.String;
    
    private var noExteriorField : System.String;
    
    private var noInteriorField : System.String;
    
    private var coloniaField : System.String;
    
    private var localidadField : System.String;
    
    private var referenciaField : System.String;
    
    private var municipioField : System.String;
    
    private var estadoField : System.String;
    
    private var paisField : System.String;
    
    private var codigoPostalField : System.String;
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get calle() : System.String {
        return this.calleField;
    }
    public final function set calle(value : System.String) {
        this.calleField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get noExterior() : System.String {
        return this.noExteriorField;
    }
    public final function set noExterior(value : System.String) {
        this.noExteriorField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get noInterior() : System.String {
        return this.noInteriorField;
    }
    public final function set noInterior(value : System.String) {
        this.noInteriorField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get colonia() : System.String {
        return this.coloniaField;
    }
    public final function set colonia(value : System.String) {
        this.coloniaField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get localidad() : System.String {
        return this.localidadField;
    }
    public final function set localidad(value : System.String) {
        this.localidadField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get referencia() : System.String {
        return this.referenciaField;
    }
    public final function set referencia(value : System.String) {
        this.referenciaField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get municipio() : System.String {
        return this.municipioField;
    }
    public final function set municipio(value : System.String) {
        this.municipioField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get estado() : System.String {
        return this.estadoField;
    }
    public final function set estado(value : System.String) {
        this.estadoField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get pais() : System.String {
        return this.paisField;
    }
    public final function set pais(value : System.String) {
        this.paisField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get codigoPostal() : System.String {
        return this.codigoPostalField;
    }
    public final function set codigoPostal(value : System.String) {
        this.codigoPostalField = value;
    }
}

///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/cfd/3") 
class t_InformacionAduanera {
    
    private var numeroField : System.String;
    
    private var fechaField : System.DateTime;
    
    private var aduanaField : System.String;
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get numero() : System.String {
        return this.numeroField;
    }
    public final function set numero(value : System.String) {
        this.numeroField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="date") 
    function get fecha() : System.DateTime {
        return this.fechaField;
    }
    public final function set fecha(value : System.DateTime) {
        this.fechaField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get aduana() : System.String {
        return this.aduanaField;
    }
    public final function set aduana(value : System.String) {
        this.aduanaField = value;
    }
}

///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/cfd/3") 
class t_Ubicacion {
    
    private var calleField : System.String;
    
    private var noExteriorField : System.String;
    
    private var noInteriorField : System.String;
    
    private var coloniaField : System.String;
    
    private var localidadField : System.String;
    
    private var referenciaField : System.String;
    
    private var municipioField : System.String;
    
    private var estadoField : System.String;
    
    private var paisField : System.String;
    
    private var codigoPostalField : System.String;
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get calle() : System.String {
        return this.calleField;
    }
    public final function set calle(value : System.String) {
        this.calleField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get noExterior() : System.String {
        return this.noExteriorField;
    }
    public final function set noExterior(value : System.String) {
        this.noExteriorField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get noInterior() : System.String {
        return this.noInteriorField;
    }
    public final function set noInterior(value : System.String) {
        this.noInteriorField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get colonia() : System.String {
        return this.coloniaField;
    }
    public final function set colonia(value : System.String) {
        this.coloniaField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get localidad() : System.String {
        return this.localidadField;
    }
    public final function set localidad(value : System.String) {
        this.localidadField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get referencia() : System.String {
        return this.referenciaField;
    }
    public final function set referencia(value : System.String) {
        this.referenciaField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get municipio() : System.String {
        return this.municipioField;
    }
    public final function set municipio(value : System.String) {
        this.municipioField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get estado() : System.String {
        return this.estadoField;
    }
    public final function set estado(value : System.String) {
        this.estadoField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get pais() : System.String {
        return this.paisField;
    }
    public final function set pais(value : System.String) {
        this.paisField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get codigoPostal() : System.String {
        return this.codigoPostalField;
    }
    public final function set codigoPostal(value : System.String) {
        this.codigoPostalField = value;
    }
}

///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
*/
class ComprobanteReceptor {
    
    //private var domicilioField : t_Ubicacion;
    
    rfcField : String;
    
    nombreField : String;
    
    /*
    ///<comentarios/>
    public final function get Domicilio() : t_Ubicacion {
        return this.domicilioField;
    }
    public final function set Domicilio(value : t_Ubicacion) {
        this.domicilioField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get rfc() : System.String {
        return this.rfcField;
    }
    public final function set rfc(value : System.String) {
        this.rfcField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get nombre() : System.String {
        return this.nombreField;
    }
    public final function set nombre(value : System.String) {
        this.nombreField = value;
    }*/
}

/*
///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
*/
class ComprobanteConcepto {
    
    //private var itemsField : System.Object[];
    
    cantidadField : number;
    
    unidadField : String;
    
    noIdentificacionField : String;
    
    descripcionField : String;
    
    valorUnitarioField : number;
    
    importeField : number;

    /*
    ///<comentarios/>
    public final System.Xml.Serialization.XmlElementAttribute("ComplementoConcepto", ComprobanteConceptoComplementoConcepto) System.Xml.Serialization.XmlElementAttribute("CuentaPredial", ComprobanteConceptoCuentaPredial) System.Xml.Serialization.XmlElementAttribute("InformacionAduanera", t_InformacionAduanera) System.Xml.Serialization.XmlElementAttribute("Parte", ComprobanteConceptoParte) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get cantidad() : decimal {
        return this.cantidadField;
    }
    public final function set cantidad(value : decimal) {
        this.cantidadField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get unidad() : System.String {
        return this.unidadField;
    }
    public final function set unidad(value : System.String) {
        this.unidadField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get noIdentificacion() : System.String {
        return this.noIdentificacionField;
    }
    public final function set noIdentificacion(value : System.String) {
        this.noIdentificacionField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get descripcion() : System.String {
        return this.descripcionField;
    }
    public final function set descripcion(value : System.String) {
        this.descripcionField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get valorUnitario() : decimal {
        return this.valorUnitarioField;
    }
    public final function set valorUnitario(value : decimal) {
        this.valorUnitarioField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get importe() : decimal {
        return this.importeField;
    }
    public final function set importe(value : decimal) {
        this.importeField = value;
    }
    */
}

///<comentarios/>
/*
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
class ComprobanteConceptoComplementoConcepto {
    
    private var anyField : System.Xml.XmlElement[];
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAnyElementAttribute() 
    function get Any() : System.Xml.XmlElement[] {
        return this.anyField;
    }
    public final function set Any(value : System.Xml.XmlElement[]) {
        this.anyField = value;
    }
}

///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
class ComprobanteConceptoCuentaPredial {
    
    private var numeroField : System.String;
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get numero() : System.String {
        return this.numeroField;
    }
    public final function set numero(value : System.String) {
        this.numeroField = value;
    }
}

///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
class ComprobanteConceptoParte {
    
    private var informacionAduaneraField : t_InformacionAduanera[];
    
    private var cantidadField : decimal;
    
    private var unidadField : System.String;
    
    private var noIdentificacionField : System.String;
    
    private var descripcionField : System.String;
    
    private var valorUnitarioField : decimal;
    
    private var valorUnitarioFieldSpecified : boolean;
    
    private var importeField : decimal;
    
    private var importeFieldSpecified : boolean;
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlElementAttribute("InformacionAduanera") 
    function get InformacionAduanera() : t_InformacionAduanera[] {
        return this.informacionAduaneraField;
    }
    public final function set InformacionAduanera(value : t_InformacionAduanera[]) {
        this.informacionAduaneraField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get cantidad() : decimal {
        return this.cantidadField;
    }
    public final function set cantidad(value : decimal) {
        this.cantidadField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get unidad() : System.String {
        return this.unidadField;
    }
    public final function set unidad(value : System.String) {
        this.unidadField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get noIdentificacion() : System.String {
        return this.noIdentificacionField;
    }
    public final function set noIdentificacion(value : System.String) {
        this.noIdentificacionField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get descripcion() : System.String {
        return this.descripcionField;
    }
    public final function set descripcion(value : System.String) {
        this.descripcionField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get valorUnitario() : decimal {
        return this.valorUnitarioField;
    }
    public final function set valorUnitario(value : decimal) {
        this.valorUnitarioField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get valorUnitarioSpecified() : boolean {
        return this.valorUnitarioFieldSpecified;
    }
    public final function set valorUnitarioSpecified(value : boolean) {
        this.valorUnitarioFieldSpecified = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get importe() : decimal {
        return this.importeField;
    }
    public final function set importe(value : decimal) {
        this.importeField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get importeSpecified() : boolean {
        return this.importeFieldSpecified;
    }
    public final function set importeSpecified(value : boolean) {
        this.importeFieldSpecified = value;
    }
}

///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
class ComprobanteImpuestos {
    
    private var retencionesField : ComprobanteImpuestosRetencion[];
    
    private var trasladosField : ComprobanteImpuestosTraslado[];
    
    private var totalImpuestosRetenidosField : decimal;
    
    private var totalImpuestosRetenidosFieldSpecified : boolean;
    
    private var totalImpuestosTrasladadosField : decimal;
    
    private var totalImpuestosTrasladadosFieldSpecified : boolean;
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlArrayItemAttribute("Retencion", IsNullable=false) 
    function get Retenciones() : ComprobanteImpuestosRetencion[] {
        return this.retencionesField;
    }
    public final function set Retenciones(value : ComprobanteImpuestosRetencion[]) {
        this.retencionesField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlArrayItemAttribute("Traslado", IsNullable=false) 
    function get Traslados() : ComprobanteImpuestosTraslado[] {
        return this.trasladosField;
    }
    public final function set Traslados(value : ComprobanteImpuestosTraslado[]) {
        this.trasladosField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get totalImpuestosRetenidos() : decimal {
        return this.totalImpuestosRetenidosField;
    }
    public final function set totalImpuestosRetenidos(value : decimal) {
        this.totalImpuestosRetenidosField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get totalImpuestosRetenidosSpecified() : boolean {
        return this.totalImpuestosRetenidosFieldSpecified;
    }
    public final function set totalImpuestosRetenidosSpecified(value : boolean) {
        this.totalImpuestosRetenidosFieldSpecified = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get totalImpuestosTrasladados() : decimal {
        return this.totalImpuestosTrasladadosField;
    }
    public final function set totalImpuestosTrasladados(value : decimal) {
        this.totalImpuestosTrasladadosField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get totalImpuestosTrasladadosSpecified() : boolean {
        return this.totalImpuestosTrasladadosFieldSpecified;
    }
    public final function set totalImpuestosTrasladadosSpecified(value : boolean) {
        this.totalImpuestosTrasladadosFieldSpecified = value;
    }
}

///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
class ComprobanteImpuestosRetencion {
    
    private var impuestoField : ComprobanteImpuestosRetencionImpuesto;
    
    private var importeField : decimal;
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get impuesto() : ComprobanteImpuestosRetencionImpuesto {
        return this.impuestoField;
    }
    public final function set impuesto(value : ComprobanteImpuestosRetencionImpuesto) {
        this.impuestoField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get importe() : decimal {
        return this.importeField;
    }
    public final function set importe(value : decimal) {
        this.importeField = value;
    }
}

///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
enum ComprobanteImpuestosRetencionImpuesto {
    
    ///<comentarios/>
    ISR,
    
    ///<comentarios/>
    IVA,
}

///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
class ComprobanteImpuestosTraslado {
    
    private var impuestoField : ComprobanteImpuestosTrasladoImpuesto;
    
    private var tasaField : decimal;
    
    private var importeField : decimal;
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get impuesto() : ComprobanteImpuestosTrasladoImpuesto {
        return this.impuestoField;
    }
    public final function set impuesto(value : ComprobanteImpuestosTrasladoImpuesto) {
        this.impuestoField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get tasa() : decimal {
        return this.tasaField;
    }
    public final function set tasa(value : decimal) {
        this.tasaField = value;
    }
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get importe() : decimal {
        return this.importeField;
    }
    public final function set importe(value : decimal) {
        this.importeField = value;
    }
}

///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
enum ComprobanteImpuestosTrasladoImpuesto {
    
    ///<comentarios/>
    IVA,
    
    ///<comentarios/>
    IEPS,
}

///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
class ComprobanteComplemento {
    
    private var anyField : System.Xml.XmlElement[];
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAnyElementAttribute() 
    function get Any() : System.Xml.XmlElement[] {
        return this.anyField;
    }
    public final function set Any(value : System.Xml.XmlElement[]) {
        this.anyField = value;
    }
}

///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
class ComprobanteAddenda {
    
    private var anyField : System.Xml.XmlElement[];
    
    ///<comentarios/>
    public final System.Xml.Serialization.XmlAnyElementAttribute() 
    function get Any() : System.Xml.XmlElement[] {
        return this.anyField;
    }
    public final function set Any(value : System.Xml.XmlElement[]) {
        this.anyField = value;
    }
}

///<comentarios/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/cfd/3") 
enum ComprobanteTipoDeComprobante {
    
    ///<comentarios/>
    ingreso,
    
    ///<comentarios/>
    egreso,
    
    ///<comentarios/>
    traslado,
}
*/
